added manual

diff --git a/.github/workflows/manual.yml b/.github/workflows/manual.yml
--- a/.github/workflows/manual.yml
+++ b/.github/workflows/manual.yml
@@ -33,9 +33,14 @@ jobs:
       run: go test -v ./...
       continue-on-error: false
 
-    - name: Create release
+    - name: Check input
       run: |
-        echo "Hello ${{ github.event.inputs.name }}"
+        echo "Version: ${{ github.event.inputs.name }}"
+        VERSION=`${{ github.event.inputs.name }}`
+        if [ "$VERSION" != "major" ] || [ "$VERSION" != "minor" ] || [ "$VERSION" != "patch" ]; then
+            echo "Error: Provided string must be 'major', 'minor', or 'patch'"
+            exit 1
+        fi
 
     - name: Create dry run tag
       uses: anothrNick/github-tag-action@1.67.0
